### ISSUE TITLE
Sidebar positioning: pushing stuff off-screen etc.

### ISSUE THREAD

**Issue by jasmith93** [LondonStudent/site#2]
Ok so the biggest issue I can see so far is that, on mobile, when opening the sidebar the article and everything in the header is pushed to the right. It means that the overall size of the webpage is increased, and I can scroll around both the sidebar and the page as if the webpage has just increased in size.

Either the sidebar needs to open up over the top of the article (so that the content doesn't move) or to keep the moving-content coolness, the header content (including the logo) needs to be changed so that it doesn't stays put and the content that moves needs the right hand side chopped off so that you can't scroll around the webpage after you've expanded the sidebar. I was thinking this could be done by putting the articles inside a box that has an endpoint wherever the edge of the user's screen is but I have no idea how that could be implemented.

**Comment by mcky** [comment]
Fixing some other sidebar issues but not entirely sure what you mean - could you put a screenshot?

**Comment by mcky** [comment]
Temporarily addressed in 6c4b19c (by making it fixed)
