### ISSUE TITLE
Varying distances between items in the sidebar ticker (newest version of firefox, chrome for android)

### ISSUE THREAD

**Issue by jasmith93** [LondonStudent/site#5]
![capture](https://cloud.githubusercontent.com/assets/10839994/7273830/43e51698-e8ef-11e4-9140-eb0d4d1c1377.PNG)

**Comment by mcky** [comment]
That's due to someone sneaking `<hr>`s into their posts @558700

**Comment by jasmith93** [comment]
Into posts? Any HR in a post will do this?

**Comment by mcky** [comment]
smh ![screen shot 2015-04-22 at 13 03 03](https://cloud.githubusercontent.com/assets/2717635/7273902/fd97ea2a-e8ef-11e4-87d3-c3c1885514ec.png)

**Comment by jasmith93** [comment]
That's gross. In the title? Who even does that?

**Comment by mcky** [comment]
:ed:
