### ISSUE TITLE
Header looks a bit funny on mobile

### ISSUE THREAD

**Issue by jasmith93** [LondonStudent/site#6]
![capture](https://cloud.githubusercontent.com/assets/10839994/7273886/ded1f77a-e8ef-11e4-8ca3-9b98046d5561.PNG)

"Got a tip?" doesn't fit - maybe em rather than pt? Assume we'll want to make this a drop down for different pages at some point. Also the logo isn't centred which looks a bit strange and I the lines for the sidebar button are too thick - they look like they should mirror the thickness of the logo (which changes obvz)

**Comment by mcky** [comment]
Button is too thick at all sizes actually, need to change that

**Comment by jasmith93** [comment]
Me and Ed have discussed and would change "Got a tip?" to Contact Us - all other info can go in the footer
