### ISSUE TITLE
We need a footer

### ISSUE THREAD

**Issue by jasmith93** [LondonStudent/site#7]
It would be good to put some info into a footer but this can be done at any point. If we get a simple implementation that looks good and we can update that in future. Basic info would just be address and contacts and legal stuff:

London Student
2nd floor, Waterstones
82 Gower St
London WC1E 6EQ

Tel: 07969592204
general@lsnews.co.uk 

© All rights to the London Student name & brand are held by the University of London. All works produced after August 2014 are by an independent group of students.

**Comment by mcky** [comment]
I think @558700 made one but didn't get a chance to push. I'll do later if no word on that.

**Comment by jasmith93** [comment]
Thanks Ross - no rush on this stuff

**Comment by mcky** [comment]
Also could there just be a link to a legal page with that © stuff? Keep it a bit cleaner

**Comment by bjacksonuk** [comment]
Community guidelines too. Those are very important to me

**Comment by jasmith93** [comment]
Depends Ross. ideally would be on every page in case it gets printed. I'm thinking this stuff will be in grey size 8 font or something though
